export const environment = {
  production: true,
  mainUrl: '/api',
  loginUser: '/login',
  signupUser: '/signup',
  updateUser: '/user',
  deleteUser: '/user',
  getSubitem: '/subitems',
  getfavourite: '/favourite',
  addToFavourite: '/favorite',
  deleteFromFavourite: '/favourite',
  rateProduct: '/rating',
  getFromCart: '/cart',
  addToCart: '/cart',
  updateQuantity: '/cart',
  deleteFromCart: '/cart',
  getAddress: '/address',
  addAddress: '/address',
  updateAddress: '/address',
  deleteAddress: '/address',
  updatePassword: '/updatePassword',
};
